using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class N : MonoBehaviour
{

    CelestialBody[] bodies;

    // Start is called before the first frame update
    void Awake()
    {
        bodies = FindObjectsOfType<CelestialBody>();
        Time.fixedDeltaTime = Universe.physicsTimeStep;
    }

    // Update is called once per frame
    void FixedUpdate()
    {
        for(int i = 0; i < bodies.Length; i++)
        {
            bodies[i].UpdateVelocity(bodies, Universe.physicsTimeStep);
        }

        for(int i = 0;i < bodies.Length; i++)
        {
            bodies[i].UpdatePosition(Universe.physicsTimeStep); 
        }
    }
}
